apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: basilvarghese/simple-frontend
    context: ./simple-frontend
  local:
    push: true
deploy:
  kubectl:
    manifests:
      - k8s/*